version: "3"

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entryPoints: https
    volumes:
      - ./config:/config
    environment:
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_KEY:?error}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_KEY:?error}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_ENCRYPTION_KEY:?error}

networks:
  traefik-proxy:
    driver: bridge
    external: true
