access_control:
  default_policy: deny
  rules:
    - domain: castelnuovo.dev
      policy: bypass

    - domain: authelia.castelnuovo.dev
      policy: bypass

    - domain: paperless.castelnuovo.dev
      policy: one_factor
      subject:
        - group:paperless

    - domain: traefik.castelnuovo.dev
      policy: two_factor
      subject:
        - group:traefik

theme: light
default_redirection_url: https://authelia.castelnuovo.dev

log:
  level: info
  file_path: /config/authelia.log
  keep_stdout: true

totp:
  disable: false
  issuer: authelia.castelnuovo.dev

webauthn:
  disable: true
  display_name: authelia.castelnuovo.dev

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  file:
    path: /config/users.yml
    watch: true

session:
  name: authelia_session
  domain: castelnuovo.dev
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 10
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
